# SPDX-License-Identifier: GPL-3.0-or-later

# combaseapi.h
COINITBASE_MULTITHREADED = 0x00

# objbase.h
COINIT_APARTMENTTHREADED = 0x02
COINIT_MULTITHREADED = COINITBASE_MULTITHREADED
COINIT_DISABLE_OLE1DDE = 0x04
COINIT_SPEED_OVER_MEMORY = 0x08

def co_initialize(coInit = COINIT_APARTMENTTHREADED):
  raise NotImplementedError
